# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      # fraza install  
      - name: Install
        run: npm install
      # fraza unit
      - name: unit-test
        run : npm run unit-tests
      # fraza integration
      - name: integration-test
        run : npm run integration-tests
      # fraza raport
      - name: Test Report unit
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
        name: mocha Tests unit
        path: ./test-results.json
        reporter: mocha-json
      # fraza depeddency check
      - name: Depcheck uses: dependency-check/Dependency-Check_Action@main id: Depcheck with:
        project: 'ms-starwars' path: '.'
        format: 'HTML' others: ''
        - name: Upload Test results uses: actions/upload-artifact@master with:
          name: Depcheck report path: ${{github.workspace}}/reports
      
      
        
